name: Rust

on:
  push:
    branches: [ "developer", "CI/CD-setting" ]
  pull_request:
    branches: [ "developer", "CI/CD-setting" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: src-tauri/cargo build --verbose
    - name: Run tests
      run: src-tauri/cargo test --verbose
