name: Rust

on:
  push:
    branches: [ "developer", "CI/CD-setting" ]
  pull_request:
    branches: [ "developer", "CI/CD-setting" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
          
    steps:
    - uses: actions/checkout@v3
    
    - name: Adding localhost to privelages
      run: xhost +SI:localuser:root
      
    - name: Tauri dependencies
      run: >-
        sudo apt-get update &&
        sudo apt-get install -y
        libgtk-3-dev
        libayatana-appindicator3-dev
        libwebkit2gtk-4.0-dev
        webkit2gtk-driver
        xvfb
    
    - name: Set Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        
    - name: Yarn install
      run: yarn install
        
    - name: Install tauri-driver
      uses: actions-rs/cargo@v1
      with:
          command: install
          args: tauri-driver
        
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    
    - name: Build
      run: |
        yarn tauri dev
        
