name: Rust

on:
  push:
    branches: [ "developer", "CI/CD-setting" ]
  pull_request:
    branches: [ "developer", "CI/CD-setting" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
          
    steps:
    - uses: actions/checkout@v3
  
    - name: Tauri dependencies
      run: >-
        sudo apt-get update &&
        sudo apt-get install -y
        libgtk-3-dev
        libayatana-appindicator3-dev
        libwebkit2gtk-4.0-dev
        webkit2gtk-driver
        xvfb
        
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: Build
      run: |
        yarn tauri dev
        
#     - name: Run tests
#       run: |
#         cd src-tauri
#         cargo test .\src\main.rs --verbose

#     steps:
#     - uses: actions/checkout@v3
#     - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
#     - name: Build
#       run: |
#         cd src-tauri
#         cargo run .\src\main.rs --verbose
#     - name: Run tests
#       run: |
#         cd src-tauri
#         cargo test .\src\main.rs --verbose
